# Generated by Django 5.1.5 on 2025-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=50, unique=True)),
                ("contraseña", models.CharField(max_length=255)),
                ("rol", models.CharField(default="admin", max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
    ]
