# Generated by Django 5.1.5 on 2025-01-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("embalse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Precipitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tres_dias_previos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cinco_dias_previos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "diez_dias_previos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fecha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embalse.embalse",
                    ),
                ),
            ],
            options={
                "db_table": "precipitacion",
            },
        ),
    ]
