# Generated by Django 5.1.5 on 2025-01-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("precipitacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precipitacion",
            name="fecha",
            field=models.DateField(),
        ),
    ]
