# Generated by Django 5.1.5 on 2025-01-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("precipitacion", "0002_alter_precipitacion_fecha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="precipitacion",
            name="cinco_dias_previos",
        ),
        migrations.RemoveField(
            model_name="precipitacion",
            name="diez_dias_previos",
        ),
        migrations.RemoveField(
            model_name="precipitacion",
            name="tres_dias_previos",
        ),
    ]
