# Generated by Django 5.1.5 on 2025-01-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instrumento", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instrumento.instrumento",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "medicion",
            },
        ),
    ]
