# Generated by Django 5.1.5 on 2025-02-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicion",
            name="id_usuario",
        ),
    ]
