# Generated by Django 5.1.5 on 2025-04-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instrumento", "0002_alter_instrumento_fecha_alta"),
        ("medicion", "0002_remove_medicion_id_usuario"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicion",
            unique_together={("id_instrumento", "fecha")},
        ),
    ]
