# Generated by Django 5.1.5 on 2025-01-31 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instrumento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumento",
            name="fecha_alta",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
